# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: 'COPYING'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.4.2
    hooks:
      - id: isort

  - repo: https://github.com/myint/rstcheck
    rev: ''
    hooks:
      - id: rstcheck

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  - repo: https://github.com/zricethezav/gitleaks
    rev: v7.6.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        stages: [commit-msg]
#  - repo: https://gitlab.com/pycqa/flake8
#    rev: 3.8.3
#    hooks:
#      - id: flake8
#        args: ["--ignore", "E501,W503,F401,E203"]
#
#  - repo: https://github.com/PyCQA/pylint
#    rev: v2.11.1
#    hooks:
#      - id: pylint
#        args: ["-d", "import-error,fixme", "-j", "4"]
#
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.782
#    hooks:
#      - id: mypy
#        additional_dependencies: [pydantic]  # add if use pydantic
#
#  - repo: https://github.com/PyCQA/bandit
#    rev: 1.7.0
#    hooks:
#      - id: bandit
#        args: ["--ini", "bandit.ini", "-ll"]
