[tool.poetry]
name = "webmon2"
version = "2.5.11"
description = ""
authors = ["Karol Będkowski <karol.bedkowski@gmail.com>"]
license = "GPL-2.0-or-later"
readme = "README.rst"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)",
    "Programming Language :: Python :: 3 :: Only",
    "Environment :: Web Environment",
    "Framework :: Flask",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
]
include = ["ChangeLog"]


[tool.poetry.dependencies]
python = "^3.7"
Werkzeug = "^2.0"
requests = "^2.21.0"
markdown2 = "^2.4"
lxml = "^4.3"
PyYAML = ">3"
feedparser = "^6.0"
html2text = "^2020.1.16"
"github3.py" = "^2.0"
Flask = "^2.0"
cssselect = "^1.1"
prometheus-client = "^0.11"
gevent = "*"
readability-lxml = "^0.8"
python-dateutil = "^2.8"
python-gitlab = "^2.10"
pyotp = { version = "^2.6", optional = true}
PyQRCode = { version = "^1.2", optional = true}
psycopg2 = "^2.8"
defusedxml = "^0.6"
Flask-Minify = { version="^0.32",  optional = true }

[tool.poetry.dev-dependencies]
pre-commit = "^2.15.0"
stackprinter = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
skip = "migrations"

[tool.poetry.scripts]
webmon2 = "webmon2.main:main"

[tool.bandit]
skips = ["B101", "B410", "B303", "B110", "B404", "B311", "B405", "B201"]

[mypy]
python_version = 3.7
