[tool.poetry]
name = "webmon2"
version = "2.5.1"
description = ""
authors = ["Karol Będkowski <karol.bedkowski@gmail.com>"]
license = "GPL-2.0-or-later"
readme = "README.rst"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)",
    "Programming Language :: Python :: 3 :: Only",
    "Environment :: Web Environment",
    "Framework :: Flask",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
]
include = ["ChangeLog"]


[tool.poetry.dependencies]
python = "^3.7"
Werkzeug = "^2.0.1"
requests = "^2.26.0"
markdown2 = "^2.4.1"
lxml = "^4.6.3"
PyYAML = "^5.4.1"
feedparser = "^6.0.8"
html2text = "^2020.1.16"
"github3.py" = "^2.0.0"
Flask = "^2.0.1"
cssselect = "^1.1.0"
prometheus-client = "^0.11.0"
gevent = "^21.8.0"
readability-lxml = "^0.8.1"
python-dateutil = "^2.8.2"
python-gitlab = "^2.10.1"
pyotp = "^2.6.0"
PyQRCode = "^1.2.1"
psycopg2 = "^2.8"

[tool.poetry.dev-dependencies]
pre-commit = "^2.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[tool.poetry.scripts]
webmon2 = "webmon2.main:main"

[tool.bandit]
skips = ["B101"]
