output:
    text:
        file: report.txt
    html:
        file: report.html
    #console:
    email:
        enabled: false
        to: foo@bar.com
        from: foo@bar.com
        subject: "WebMon"
        smtp_host: smtp.foo.bar
        smtp_port: 465
        smtp_login: login
        smtp_password: password
        smtp_ssl: true
        #smtp_tls: true
        html: true
defaults:
    interval: 10m
    report_unchanged: false
    github_user: login
    github_token: 1111111111111111111111111111111111111111
    jamendo_client_id: 00000000
stats:
    # when set, create stats file for prometheus collector
    #prometheus_output: webmon.prom
